import { expect, test } from '@playwright/test'
import { savedChat, seedChat } from './chat-fixtures'

test('Enter anchors a new question under the header, follows growth and respects manual reading', async ({ page }) => {
  await seedChat(page, savedChat(60))
  await page.goto('/')
  await expect(page.locator('.chat-workspace')).toHaveAttribute('data-ready', 'true', { timeout: 15_000 })
  const input = page.getByRole('textbox', { name: 'Nachricht', exact: true })
  await input.fill('/lang')
  await page.clock.install()
  await page.clock.pauseAt(new Date(await page.evaluate(() => Date.now()) + 100))
  await input.press('Enter')
  await expect(input).toBeFocused()
  const scroll = page.locator('.chat-scroll')
  const question = page.locator('.message-user').last()
  await page.clock.runFor(50)
  const header = await page.locator('.chat-header').boundingBox()
  const box = await question.boundingBox()
  expect(box!.y - (header!.y + header!.height)).toBeGreaterThanOrEqual(0)
  expect(box!.y - (header!.y + header!.height)).toBeLessThan(40)
  const startTop = await scroll.evaluate(element => element.scrollTop)
  await page.clock.runFor(6000)
  expect(await scroll.evaluate(element => element.scrollTop)).toBeGreaterThan(startTop)
  expect(await scroll.evaluate(element => element.scrollHeight - element.clientHeight - element.scrollTop)).toBeLessThan(3)
  await scroll.evaluate(element => { element.scrollTop -= 600; element.dispatchEvent(new Event('scroll')) })
  const readingTop = await scroll.evaluate(element => element.scrollTop)
  await page.clock.runFor(1000)
  expect(await scroll.evaluate(element => element.scrollTop)).toBeCloseTo(readingTop, 0)
  await expect(page.getByRole('button', { name: 'Zum Ende scrollen' })).toBeVisible()
  await page.getByRole('button', { name: 'Zum Ende scrollen' }).click()
  await page.clock.runFor(500)
  expect(await scroll.evaluate(element => element.scrollHeight - element.clientHeight - element.scrollTop)).toBeLessThan(3)
  await expect(page.locator('[data-generation-status]')).toHaveAttribute('data-generation-status', 'streaming')
  await page.getByRole('button', { name: 'Antwort stoppen', exact: true }).click()
  await page.clock.runFor(50)
  await expect(page.locator('.message-assistant').last()).toHaveAttribute('data-status', 'cancelled')
})

test('chat switching restores reading position and the sidebar scrolls independently', async ({ page }) => {
  await seedChat(page, savedChat(80))
  await page.goto('/')
  await expect(page.locator('.chat-workspace')).toHaveAttribute('data-ready', 'true', { timeout: 15_000 })
  const scroll = page.locator('.chat-scroll')
  await scroll.evaluate(element => { element.scrollTop = 1500; element.dispatchEvent(new Event('scroll')) })
  const position = await scroll.evaluate(element => element.scrollTop)
  const toggle = page.locator('.chat-header button[aria-controls="chat-sidebar"]')
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  const navigation = page.getByRole('navigation', { name: 'Gespräche' })
  await navigation.getByRole('button', { name: 'Gedanken 1', exact: true }).click()
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  await navigation.getByRole('button', { name: 'Unser Gespräch', exact: true }).click()
  await expect.poll(() => scroll.evaluate(element => element.scrollTop)).toBeCloseTo(position, 0)
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  await navigation.getByRole('button', { name: 'Gedanken 44', exact: true }).scrollIntoViewIfNeeded()
  expect(await scroll.evaluate(element => element.scrollTop)).toBeCloseTo(position, 0)
})

test('shortcuts, focus, reduced motion and a resized keyboard viewport stay usable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.chat-workspace')).toHaveAttribute('data-ready', 'true', { timeout: 15_000 })
  await page.keyboard.press('Control+Shift+O')
  const input = page.getByRole('textbox', { name: 'Nachricht', exact: true })
  await expect(input).toBeFocused()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'Chats suchen' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Chats suchen' })).not.toBeVisible()
  const original = page.viewportSize()!
  await page.setViewportSize({ width: original.width, height: 420 })
  await input.fill('Auf dem kleinen Bildschirm')
  await expect(page.getByRole('button', { name: 'Nachricht senden', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await input.press('Enter')
  await expect(input).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.locator('.message-assistant')).toHaveAttribute('data-status', 'cancelled')
  const touch = await page.getByRole('button', { name: 'Nachricht senden', exact: true }).boundingBox()
  expect(touch!.height).toBeGreaterThanOrEqual(44)
  expect(touch!.width).toBeGreaterThanOrEqual(44)
})
