"""Chat persistence tables (Etappe 3).

Conversations, immutable message tree, generations, replayable stream
events, drafts and per-owner preferences. Grants DML to the restricted
application role when the bootstrap role exists.

Revision ID: 0002_chat_persistence
Revises: 0001_foundation
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_chat_persistence"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The restricted application role is created by the PostgreSQL bootstrap
# script; disposable test databases may run without it.
GRANT_DML = """
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'noris_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
      chat_conversation, chat_message, chat_generation,
      chat_stream_event, chat_draft, chat_user_preferences
    TO noris_app;
  END IF;
END
$$;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "title_source",
            sa.Enum("fallback", "generated", "manual", name="chat_title_source"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_leaf_message_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "length(title) > 0 AND length(title) <= 200",
            name=op.f("ck_chat_conversation_title_length"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_chat_conversation_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_conversation")),
    )
    op.create_index(
        "ix_chat_conversation_owner_updated",
        "chat_conversation",
        ["owner_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "chat_draft",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("draft_key", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(draft_key) > 0 AND length(draft_key) <= 64",
            name=op.f("ck_chat_draft_key_length"),
        ),
        sa.PrimaryKeyConstraint("owner_id", "draft_key", name=op.f("pk_chat_draft")),
    )
    op.create_table(
        "chat_generation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("input_message_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_message_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "cancelled",
                "failed",
                "interrupted",
                name="chat_generation_status",
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            (
                "output_tokens IS NULL AND input_tokens IS NULL"
                " OR output_tokens IS NOT NULL AND input_tokens IS NOT NULL"
            ),
            name=op.f("ck_chat_generation_usage_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["chat_conversation.id"], name="fk_chat_generation_conversation"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_generation")),
    )
    op.create_index(
        "ix_chat_generation_conversation", "chat_generation", ["conversation_id"], unique=False
    )
    op.create_index("ix_chat_generation_status", "chat_generation", ["status"], unique=False)
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("parent_message_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.Enum("user", "assistant", name="chat_message_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "streaming",
                "completed",
                "cancelled",
                "failed",
                name="chat_message_status",
            ),
            nullable=False,
        ),
        sa.Column("generation_id", sa.Uuid(), nullable=True),
        sa.Column("edited_from_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(content) <= 128000", name=op.f("ck_chat_message_content_length")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "edited_from_message_id"],
            ["chat_message.conversation_id", "chat_message.id"],
            name="edited_from",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "parent_message_id"],
            ["chat_message.conversation_id", "chat_message.id"],
            name="parent",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chat_conversation.id"],
            name=op.f("fk_chat_message_conversation_id_chat_conversation"),
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["chat_generation.id"],
            name=op.f("fk_chat_message_generation_id_chat_generation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_message")),
        sa.UniqueConstraint("conversation_id", "id", name="uq_chat_message_conversation_id"),
    )
    op.create_index(
        "ix_chat_message_conversation_created",
        "chat_message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    # Deferred circular constraint: the active leaf belongs to this conversation.
    op.create_foreign_key(
        "active_leaf",
        "chat_conversation",
        "chat_message",
        ["id", "active_leaf_message_id"],
        ["conversation_id", "id"],
    )
    # Deferred circular constraints: generation inputs and assistant message.
    op.create_foreign_key(
        "input_message",
        "chat_generation",
        "chat_message",
        ["conversation_id", "input_message_id"],
        ["conversation_id", "id"],
    )
    op.create_foreign_key(
        "assistant_message",
        "chat_generation",
        "chat_message",
        ["conversation_id", "assistant_message_id"],
        ["conversation_id", "id"],
    )
    op.create_table(
        "chat_stream_event",
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_chat_stream_event_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["generation_id"], ["chat_generation.id"], name="fk_chat_stream_event_generation"
        ),
        sa.PrimaryKeyConstraint("generation_id", "sequence", name="pk_chat_stream_event"),
    )
    op.create_index(
        "ix_chat_stream_event_created", "chat_stream_event", ["created_at"], unique=False
    )
    op.create_index(
        "ix_chat_stream_event_generation_sequence",
        "chat_stream_event",
        ["generation_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "chat_user_preferences",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("active_conversation_id", sa.Uuid(), nullable=True),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_conversation_id"],
            ["chat_conversation.id"],
            name=op.f("fk_chat_user_preferences_active_conversation_id_chat_conversation"),
        ),
        sa.PrimaryKeyConstraint("owner_id", name=op.f("pk_chat_user_preferences")),
    )
    # ### end Alembic commands ###
    # DML for the restricted application role (SELECT-only default otherwise).
    op.execute(GRANT_DML)


def downgrade() -> None:
    # Drop deferred and circular foreign keys before the mutually dependent tables.
    op.drop_constraint("active_leaf", "chat_conversation", type_="foreignkey")
    op.drop_constraint("input_message", "chat_generation", type_="foreignkey")
    op.drop_constraint("assistant_message", "chat_generation", type_="foreignkey")
    op.drop_constraint("parent", "chat_message", type_="foreignkey")
    op.drop_constraint("edited_from", "chat_message", type_="foreignkey")
    op.drop_constraint(
        "fk_chat_message_generation_id_chat_generation", "chat_message", type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_user_preferences")
    op.drop_index("ix_chat_stream_event_generation_sequence", table_name="chat_stream_event")
    op.drop_index("ix_chat_stream_event_created", table_name="chat_stream_event")
    op.drop_table("chat_stream_event")
    op.drop_index("ix_chat_message_conversation_created", table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index("ix_chat_generation_status", table_name="chat_generation")
    op.drop_index("ix_chat_generation_conversation", table_name="chat_generation")
    op.drop_table("chat_generation")
    op.drop_table("chat_draft")
    op.drop_index("ix_chat_conversation_owner_updated", table_name="chat_conversation")
    op.drop_table("chat_conversation")
    op.execute("DROP TYPE chat_title_source")
    op.execute("DROP TYPE chat_message_role")
    op.execute("DROP TYPE chat_message_status")
    op.execute("DROP TYPE chat_generation_status")
    # ### end Alembic commands ###
